import "./globals.css";
import iranSansFont from "@/constants/localFont";

export const metadata = {
  title: "رینوفای صفحه اصلی",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`h-full bg-gray-100 ${iranSansFont.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
